export const sessions = [
  {
    id: 'push',
    name: 'Push',
    subtitle: 'Chest, Shoulders, Triceps',
    day: 'Tuesday',
    warmup: 'Light 5-minute cardio, arm circles, band pull-aparts, 2 warm-up sets of bench press at 50% working weight.',
    exercises: [
      {
        id: 'bench_press',
        name: 'Barbell Bench Press',
        equipment: 'barbell',
        compound: true,
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        startWeight: 60,
        progressionKg: 2.5,
        rest: 150,
        cue: 'Retract shoulder blades, plant feet flat, drive through heels.',
        note: 'Flat bench, medium grip'
      },
      {
        id: 'incline_db_press',
        name: 'Incline Dumbbell Press',
        equipment: 'dumbbell',
        compound: false,
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        startWeight: 20,
        progressionKg: 2,
        rest: 90,
        cue: 'Bench at 30-degree angle, squeeze at the top.',
        note: '30° incline, neutral to pronated grip'
      },
      {
        id: 'db_ohp',
        name: 'Dumbbell Overhead Press',
        equipment: 'dumbbell',
        compound: false,
        sets: 3,
        repsMin: 8,
        repsMax: 10,
        startWeight: 16,
        progressionKg: 2,
        rest: 90,
        cue: 'Brace core, press slightly in front of head, full lockout.',
        note: 'Seated or standing, palms forward'
      },
      {
        id: 'cable_lat_raise',
        name: 'Cable Lateral Raise',
        equipment: 'cable',
        compound: false,
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        startWeight: 5,
        progressionKg: 1,
        rest: 60,
        cue: 'Slight lean away from cable, lead with elbow, stop at shoulder height.',
        note: 'Each side, low pulley behind body'
      },
      {
        id: 'cable_pushdown',
        name: 'Cable Tricep Pushdown',
        equipment: 'cable',
        compound: false,
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        startWeight: 15,
        progressionKg: 2.5,
        rest: 60,
        cue: 'Elbows pinned to sides, squeeze at full extension.',
        note: 'Rope or straight bar attachment'
      },
      {
        id: 'overhead_tricep_ext',
        name: 'Overhead Cable Tricep Extension',
        equipment: 'cable',
        compound: false,
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        startWeight: 12,
        progressionKg: 2.5,
        rest: 60,
        cue: 'Face away from cable, stretch at bottom, lock out overhead.',
        note: 'Rope attachment, high pulley'
      }
    ],
    finisher: {
      name: 'Shoulder Finisher',
      subtitle: 'Extra lateral and front delt volume',
      exercises: [
        {
          id: 'db_lat_raise',
          name: 'Dumbbell Lateral Raise',
          equipment: 'dumbbell',
          compound: false,
          sets: 3,
          repsMin: 15,
          repsMax: 20,
          startWeight: 8,
          progressionKg: 2,
          rest: 45,
          cue: 'Slight forward lean, thumbs slightly down, control the negative.',
          note: 'Light weight, high reps, feel the burn'
        },
        {
          id: 'db_front_raise',
          name: 'Dumbbell Front Raise',
          equipment: 'dumbbell',
          compound: false,
          sets: 2,
          repsMin: 12,
          repsMax: 12,
          startWeight: 8,
          progressionKg: 2,
          rest: 45,
          cue: 'Alternating arms, stop at eye level, slow negative.',
          note: 'Each side, alternating'
        },
        {
          id: 'cable_upright_row',
          name: 'Cable Upright Row',
          equipment: 'cable',
          compound: false,
          sets: 2,
          repsMin: 12,
          repsMax: 15,
          startWeight: 15,
          progressionKg: 2.5,
          rest: 60,
          cue: 'Wide grip, pull to upper chest, elbows high and wide.',
          note: 'Straight bar, shoulder-width grip'
        }
      ]
    }
  },
  {
    id: 'pull',
    name: 'Pull',
    subtitle: 'Back, Biceps, Rear Delts',
    day: 'Friday',
    warmup: 'Light 5-minute row or bike, band pull-aparts, dead hangs, 2 warm-up sets of landmine rows at 50% working weight.',
    exercises: [
      {
        id: 'landmine_row',
        name: 'Landmine Row',
        equipment: 'barbell',
        compound: true,
        sets: 4,
        repsMin: 8,
        repsMax: 10,
        startWeight: 40,
        progressionKg: 2.5,
        rest: 150,
        cue: 'Hinge at hips, pull to hip, squeeze shoulder blade back.',
        note: 'Barbell in corner or landmine attachment'
      },
      {
        id: 'lat_pulldown',
        name: 'Lat Pulldown',
        equipment: 'cable',
        compound: false,
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        startWeight: 50,
        progressionKg: 2.5,
        rest: 90,
        cue: 'Lean slightly back, pull to upper chest, drive elbows down.',
        note: 'Wide grip, overhand'
      },
      {
        id: 'seated_cable_row',
        name: 'Seated Cable Row',
        equipment: 'cable',
        compound: false,
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        startWeight: 45,
        progressionKg: 2.5,
        rest: 90,
        cue: 'Chest up, pull to lower sternum, pause at contraction.',
        note: 'V-bar or close-grip handle'
      },
      {
        id: 'face_pulls',
        name: 'Face Pulls',
        equipment: 'cable',
        compound: false,
        sets: 3,
        repsMin: 15,
        repsMax: 20,
        startWeight: 12,
        progressionKg: 2.5,
        rest: 60,
        cue: 'Pull to forehead, externally rotate at end, hold 1 second.',
        note: 'Rope attachment, high pulley'
      },
      {
        id: 'incline_db_curl',
        name: 'Incline Dumbbell Curl',
        equipment: 'dumbbell',
        compound: false,
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        startWeight: 12,
        progressionKg: 2,
        rest: 60,
        cue: 'Let arms hang fully, curl with supination, no swinging.',
        note: '45° incline bench'
      },
      {
        id: 'hammer_curl',
        name: 'Hammer Curl',
        equipment: 'dumbbell',
        compound: false,
        sets: 2,
        repsMin: 12,
        repsMax: 15,
        startWeight: 14,
        progressionKg: 2,
        rest: 60,
        cue: 'Neutral grip, elbows stationary, squeeze at top.',
        note: 'Standing, both arms or alternating'
      }
    ],
    finisher: {
      name: 'Arms Finisher',
      subtitle: 'Extra bicep and tricep volume',
      exercises: [
        {
          id: 'ez_bar_curl',
          name: 'EZ Bar Curl',
          equipment: 'barbell',
          compound: false,
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          startWeight: 20,
          progressionKg: 2.5,
          rest: 60,
          cue: 'Slight forward lean at start, strict curl, squeeze at top.',
          note: 'Inner grip on EZ bar'
        },
        {
          id: 'cable_conc_curl',
          name: 'Cable Concentration Curl',
          equipment: 'cable',
          compound: false,
          sets: 2,
          repsMin: 12,
          repsMax: 15,
          startWeight: 8,
          progressionKg: 2.5,
          rest: 45,
          cue: 'Elbow braced on inner thigh, full stretch at bottom.',
          note: 'Each side, low pulley'
        },
        {
          id: 'db_skullcrusher',
          name: 'Dumbbell Skullcrusher',
          equipment: 'dumbbell',
          compound: false,
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          startWeight: 10,
          progressionKg: 2,
          rest: 60,
          cue: 'Lower to temples, keep elbows narrow, extend fully.',
          note: 'Flat bench, dumbbells neutral grip'
        }
      ]
    }
  },
  {
    id: 'legs',
    name: 'Legs',
    subtitle: 'Quads, Hamstrings, Glutes, Calves',
    day: 'Sunday',
    warmup: 'Light 5-minute bike or walk, leg swings, bodyweight squats, 2 warm-up sets of back squats at 50% working weight.',
    exercises: [
      {
        id: 'back_squat',
        name: 'Barbell Back Squat',
        equipment: 'barbell',
        compound: true,
        sets: 4,
        repsMin: 6,
        repsMax: 8,
        startWeight: 60,
        progressionKg: 2.5,
        rest: 150,
        cue: 'Brace hard, break at hips and knees together, hit parallel.',
        note: 'High bar, shoulder-width stance'
      },
      {
        id: 'glute_bridge',
        name: 'Barbell Glute Bridge',
        equipment: 'barbell',
        compound: false,
        sets: 4,
        repsMin: 10,
        repsMax: 12,
        startWeight: 40,
        progressionKg: 2.5,
        rest: 90,
        cue: 'Drive through heels, squeeze glutes at top, hold 1 second.',
        note: 'Pad on barbell, shoulders on bench'
      },
      {
        id: 'leg_press',
        name: 'Leg Press',
        equipment: 'machine',
        compound: false,
        sets: 3,
        repsMin: 10,
        repsMax: 12,
        startWeight: 100,
        progressionKg: 5,
        rest: 90,
        cue: 'Feet shoulder-width, lower until 90° knee bend, push through whole foot.',
        note: 'Medium-high foot placement'
      },
      {
        id: 'seated_leg_curl',
        name: 'Seated Leg Curl',
        equipment: 'machine',
        compound: false,
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        startWeight: 30,
        progressionKg: 5,
        rest: 75,
        cue: 'Curl all the way back, slow eccentric, squeeze hamstrings.',
        note: 'Adjust pad to sit above Achilles'
      },
      {
        id: 'lying_leg_curl',
        name: 'Lying Leg Curl',
        equipment: 'machine',
        compound: false,
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        startWeight: 25,
        progressionKg: 5,
        rest: 75,
        cue: 'Hips flat on pad, curl to glutes, 2-second negative.',
        note: 'Keep hips pressed down throughout'
      },
      {
        id: 'leg_extension',
        name: 'Leg Extension',
        equipment: 'machine',
        compound: false,
        sets: 3,
        repsMin: 12,
        repsMax: 15,
        startWeight: 35,
        progressionKg: 5,
        rest: 75,
        cue: 'Full extension, squeeze quads at top, control the descent.',
        note: 'Adjust backrest so knees align with pivot'
      },
      {
        id: 'calf_raise',
        name: 'Standing Calf Raise',
        equipment: 'machine',
        compound: false,
        sets: 4,
        repsMin: 15,
        repsMax: 20,
        startWeight: 40,
        progressionKg: 5,
        rest: 45,
        cue: 'Full stretch at bottom, explosive push up, hold at top.',
        note: 'Toes forward, full range of motion'
      }
    ],
    finisher: null
  }
];
